<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.nuevooooooo</groupId>
        <artifactId>java-puzzle-bloques-libgdx-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>core</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx</artifactId>
            <version>${gdx.version}</version>
        </dependency>
        <dependency>
            <groupId>com.badlogicgames.ashley</groupId>
            <artifactId>ashley</artifactId>
            <version>${ashley.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.mgsx-dev.gdx-gltf</groupId>
            <artifactId>gltf</artifactId>
            <version>${gdx-gltf.version}</version>
        </dependency>
    </dependencies>
</project>
