apply plugin: "java"

dependencies {
    implementation project(":core")
    implementation "com.github.xpenatan.gdx-teavm:backend-web:$gdxTeaVMVersion"
}

tasks.register("gdx_teavm_web_js_build", JavaExec) {
    group = "gdx-teavm"
    description = "Compila CodeQuest para navegador (JavaScript)"
    mainClass = "com.nuevooooooo.puzzle.teavm.BuildCodeQuestWeb"
    classpath = sourceSets.main.runtimeClasspath
    workingDir = projectDir
    args "build"
}

tasks.register("gdx_teavm_web_js_run", JavaExec) {
    group = "gdx-teavm"
    description = "Compila y sirve CodeQuest en http://localhost:8082"
    mainClass = "com.nuevooooooo.puzzle.teavm.BuildCodeQuestWeb"
    classpath = sourceSets.main.runtimeClasspath
    workingDir = projectDir
    args "run"
}
